---
- name: Add user to sudoers without password
  hosts: all
  become: true
  tasks:
    - name: Add user to sudoers without password
      lineinfile:
        path: /etc/sudoers
        line: "ahsan ALL=(ALL) NOPASSWD: ALL"
        validate: visudo -cf %s
