---
- name: Add user 'ahsan' to sudoers
  hosts: all
  become: true
  tasks:
    - name: Add user 'ahsan' to sudoers
      lineinfile:
        path: /etc/sudoers
        line: "ahsan ALL=(ALL:ALL) ALL"
        validate: visudo -cf %s


